  export WIFI_SSID=""
  export WIFI_PASS=""
  export MQTT_SERVER=""
  export MQTT_USER=""
  export MQTT_PASS=""
  export MQTT_TOPIC="sensors/location_01"

  export INFLUXDB_HOST="127.0.0.1"
  export INFLUXDB_PORT="8086"
  export INFLUXDB_USER="admin"
  export INFLUXDB_PASS=""
  export INFLUXDB_DBNAME="sensors"